### ISSUE TITLE
Treehouse courses to be completed

### ISSUE THREAD

**Issue by danyfebrero** [danyfebrero/treehouse#2]
## TODO

*Courses left to complete in TreeHouse*
* [ ] [CSS Layout Basics](https://teamtreehouse.com/library/css-layout-basics)
* [ ] [CSS Selectors Quickstart](https://teamtreehouse.com/library/css-selectors-quickstart)
* [ ] [Using CSS Variables](https://teamtreehouse.com/library/using-css-variables)
* [ ] [Mobile-First CSS Layout](https://teamtreehouse.com/library/mobilefirst-css-layout)
* [ ] [CSS Grid Layout](https://teamtreehouse.com/library/css-grid-layout)
* [ ] [CSS Transitions and Transform](https://teamtreehouse.com/library/css-transitions-and-transforms)
* [ ] [CSS Flexbox Layout](https://teamtreehouse.com/library/css-flexbox-layout)
* [ ] [Bootstrap 4 Basics](https://teamtreehouse.com/library/bootstrap-4-basics-2)
* [ ] [Others CSS workshop by Guil Hernadez](https://teamtreehouse.com/guil)
* [ ] [Introduction to Algorithms](https://teamtreehouse.com/library/introduction-to-algorithms)
* [ ] [Computer Science](https://teamtreehouse.com/library/topic:computer-science)
